error_on_line_overflow = false
where_style = "Rfc"
control_style = "Rfc"
wrap_comments = true
use_try_shorthand = true
attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
imports_layout = "Vertical"
imports_indent = "Block"
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true